$LOAD_PATH.unshift(File.dirname(__FILE__))

require 'rake'
require 'rspec/core/rake_task'
require 'db/config'

desc 'create the database'
task 'db:create' do
  touch 'db/stock_exchange.sqlite3'
end

desc 'drop the database'
task 'db:drop' do
  rm_f 'db/stock_exchange.sqlite3'
end

desc 'Empty the database'
task 'db:empty' do

end

desc 'remake db'
task 'db:reload' => %w(db:drop db:create db:migrate db:populate) do

end

desc "migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)."
task "db:migrate" do
  ActiveRecord::Migrator.migrations_paths << File.dirname(__FILE__) + 'db/migrate'
  ActiveRecord::Migration.verbose = ENV["VERBOSE"] ? ENV["VERBOSE"] == "true" : true
  ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths, ENV["VERSION"] ? ENV["VERSION"].to_i : nil) do |migration|
    ENV["SCOPE"].blank? || (ENV["SCOPE"] == migration.scope)
  end
end

desc 'populate the test database with sample data'
task 'db:populate' do
  require 'db/populate/stock_list_populator'
end

desc 'Retrieves the current schema version number'
task 'db:version' do
  puts "Current version: #{ActiveRecord::Migrator.current_version}"
end

desc 'boots into console'
task 'console' do
  exec 'irb -r./run_exchange'
end

desc 'Run the specs'
RSpec::Core::RakeTask.new(:specs) do |t|
  t.rspec_opts = '-I . ./app'
end

task :default  => :specs
